# FROM denoland/deno:bin AS deno
# FROM lukechannings/deno AS deno

# FROM mcr.microsoft.com/devcontainers/typescript-node:20
FROM buildpack-deps:bookworm-scm

# COPY --from=deno /deno /usr/local/bin/deno

RUN apt-get update && apt-get install -y xz-utils

SHELL ["/bin/bash", "-c"]

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends unzip iputils-ping zsh

# postgresql client
RUN echo "deb https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get -y install postgresql-client-16

# python
RUN apt-get -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
RUN apt-get -y install python3

# user node
ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash \
  && apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

# ENV HOME /home/node
USER node

# [Optional] Uncomment if you want to install more global node modules
# RUN npm install -g <your-package-list-here>

# nvm
ENV NODE_VERSION=20.18.0
ENV NVM_VERSION=0.40.1

RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash \
  && . ~/.nvm/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV PATH="/home/node/.nvm/versions/node/v$NODE_VERSION/bin:$PATH"

# yarn
RUN corepack enable yarn

# bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/home/node/.bun/bin:$PATH"

# deno
# RUN deno install -A --no-check -r -f https://deno.land/x/deploy/deployctl.ts
# ENV PATH="/home/node/.deno/bin:$PATH"

# oh-my-zsh
# RUN wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

ENV SHELL=/bin/zsh
